use std::fmt;
use std::string::FromUtf8Error;

pub mod ast;
pub mod lex;
pub mod parse;
pub mod parsec;

#[derive(Clone, Debug)]
pub enum CompileErr {
    // Because these two are generated by the lexer, we can't inspect the
    // location of the head token to determine the location of the failure
    IntOverflow(SourceLoc),
    BadEscape(SourceLoc),
    ValMismatch(lex::Token, lex::Token),
    TypeMismatch(lex::TokenDiscriminants, lex::Token),
    // TODO: Need list of valid matches here? Hard to auto-deduce
    OneOfFailure(lex::Token),
    InvalidEnumType(String),
    Message(&'static str),
    DynMessage(String),
}

impl From<FromUtf8Error> for CompileErr {
    fn from(e: FromUtf8Error) -> Self {
        CompileErr::DynMessage(e.to_string())
    }
}

impl fmt::Display for CompileErr {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::IntOverflow(_) => write!(f, "Integer too large to fit in u64"),
            Self::BadEscape(_) => write!(f, "Invalid escape sequence"),
            Self::ValMismatch(e, a) => write!(f, "Expected token {} but got {}", e, a),
            Self::TypeMismatch(e, a) => write!(f, "Expected token {} but got {}", e, a),
            Self::OneOfFailure(a) => write!(f, "Unexpected token {}", a),
            Self::InvalidEnumType(tn) => write!(f, "Invalid type for enum {}", tn),
            Self::Message(m) => write!(f, "{}", m),
            Self::DynMessage(m) => write!(f, "{}", m),
        }
    }
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub struct SourceLoc {
    pub row: i32,
    pub col: i32,
    pub off: usize,
    pub len: usize,
}

pub const SL_NIL: SourceLoc = SourceLoc {
    row: 0,
    col: 0,
    off: usize::MAX,
    len: usize::MAX,
};

pub const SL_BEGIN: SourceLoc = SourceLoc {
    row: 1,
    col: 1,
    off: 0,
    len: 0,
};

impl SourceLoc {
    pub fn new(row: i32, col: i32, off: usize, len: usize) -> SourceLoc {
        SourceLoc { row, col, off, len }
    }
    pub fn next(&mut self, ch: char) {
        if ch == '\n' {
            self.row += 1;
            self.col = 1;
        } else {
            self.col += 1;
        }

        self.off += ch.len_utf8();
    }

    pub fn to(&self, end: &SourceLoc) -> SourceLoc {
        if self.off == usize::MAX || end.off == usize::MAX {
            SL_NIL
        } else {
            SourceLoc {
                row: self.row,
                col: self.col,
                off: self.off,
                len: end.off - self.off,
            }
        }
    }

    pub fn to_right(&self, end: &SourceLoc) -> SourceLoc {
        if self.off == usize::MAX || end.off == usize::MAX {
            SL_NIL
        } else {
            SourceLoc {
                row: self.row,
                col: self.col,
                off: self.off,
                len: end.off + end.len - self.off,
            }
        }
    }

    //pub fn accum(&mut self, other: &SourceLoc) {
    //    if other.off == usize::MAX {
    //    } else if self.off == usize::MAX {
    //        *self = *other;
    //    } else {
    //        let rightmost = std::cmp::max(self.off + self.len, other.off + other.len);
    //        if self.off > other.off {
    //            self.row = other.row;
    //            self.col = other.col;
    //            self.off = other.off;
    //        }
    //        self.len = rightmost - self.off;
    //    }
    //}
}

#[derive(PartialEq, Debug)]
pub struct LocationAnnot<T> {
    pub loc: SourceLoc,
    pub inner: T,
}

impl<T: fmt::Display> fmt::Display for LocationAnnot<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.inner.fmt(f)
    }
}

impl<T> LocationAnnot<T> {
    pub fn new(loc: SourceLoc, inner: T) -> Self {
        Self { loc, inner }
    }
}

pub fn annot<T>(loc: SourceLoc, inner: T) -> LocationAnnot<T> {
    LocationAnnot::new(loc, inner)
}

pub fn annot_nil<T>(inner: T) -> LocationAnnot<T> {
    LocationAnnot::new(SL_NIL, inner)
}
